FROM public.ecr.aws/lambda/python:3.9

ADD https://github.com/snyk/snyk/releases/download/v1.367.0/snyk-linux /usr/local/bin/snyk
RUN chmod a+x /usr/local/bin/snyk

ADD requirements.txt .

# ADD app app
COPY app ${LAMBDA_TASK_ROOT}

RUN pip install -r requirements.txt
CMD ["app.lambda_handler"]
